version: '3'

services:
  app:
    build: .
    container_name: markdown-viewer
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm run dev -- --host 0.0.0.0" 